---

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push container image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build the Docker Image
        run: docker build . -t ghcr.io/The-OpenPlatform/backend -f Dockerfile --target production

